### ISSUE TITLE
Drivers not working for Cosmic OS

### ISSUE THREAD

**Issue by TomT15** [dlundqvist/xone#141]
It seems that the drivers installed successfully. I followed all the instructions to a T but still have no been able to get the lights working on the usb drive or anything else after a few restarts and reinstallations

**Comment by Lawstorant** [comment]
Could you give any basic info about your system and the output of ibstallation/how dis you install?

We're not clairvoyant, we won't magically know that

**Comment by TomT15** [comment]
im having the same experience on Ubuntu  LTS as well. im not familiar with driver logs and where to find it but what i gathered from the install was

```
Installing xone unknown...
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der
Creating symlink /var/lib/dkms/xone/unknown/source -> /usr/src/xone-unknown

Building module:
Cleaning build area...
make -j16 KERNELRELEASE=6.14.0-36-generic -C /lib/modules/6.14.0-36-generic/build M=/var/lib/dkms/xone/unknown/build...(bad exit status: 2)
ERROR (dkms apport): binary package for xone: unknown not found
Error! Bad return status for module build on kernel: 6.14.0-36-generic (x86_64)
Consult /var/lib/dkms/xone/unknown/build/make.log for more information.
DKMS make.log for xone-unknown for kernel 6.14.0-36-generic (x86_64)
Sat Nov 22 02:17:46 PM CST 2025
make: Entering directory '/usr/src/linux-headers-6.14.0-36-generic'
make[1]: Entering directory '/var/lib/dkms/xone/unknown/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  transport/wired.o
  CC [M]  transport/dongle.o
  CC [M]  transport/mt76.o
  CC [M]  bus/bus.o
  CC [M]  bus/protocol.o
  CC [M]  auth/auth.o
  CC [M]  auth/crypto.o
  CC [M]  driver/common.o
  CC [M]  driver/gamepad.o
  CC [M]  driver/headset.o
  CC [M]  driver/chatpad.o
  CC [M]  driver/madcatz_strat.o
  CC [M]  driver/madcatz_glam.o
  CC [M]  driver/pdp_jaguar.o
bus/bus.c:126:18: error: initialization of ‘int (*)(struct device *, const struct device_driver *)’ from incompatible pointer type ‘int (*)(struct device *, struct device_driver *)’ [-Werror=incompatible-pointer-types]
  126 |         .match = gip_bus_match,
      |                  ^~~~~~~~~~~~~
bus/bus.c:126:18: note: (near initialization for ‘gip_bus_type.match’)
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-6.14.0-36-generic/scripts/Makefile.build:207: bus/bus.o] Error 1
make[3]: *** Waiting for unfinished jobs....
driver/headset.c: In function ‘gip_headset_pcm_hw_params’:
driver/headset.c:93:16: error: implicit declaration of function ‘snd_pcm_lib_alloc_vmalloc_buffer’ [-Werror=implicit-function-declaration]
   93 |         return snd_pcm_lib_alloc_vmalloc_buffer(sub,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
driver/headset.c: In function ‘gip_headset_pcm_hw_free’:
driver/headset.c:99:16: error: implicit declaration of function ‘snd_pcm_lib_free_vmalloc_buffer’; did you mean ‘snd_pcm_lib_malloc_pages’? [-Werror=implicit-function-declaration]
   99 |         return snd_pcm_lib_free_vmalloc_buffer(sub);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                snd_pcm_lib_malloc_pages
driver/headset.c: At top level:
driver/headset.c:160:17: error: ‘snd_pcm_lib_get_vmalloc_page’ undeclared here (not in a function); did you mean ‘snd_pcm_lib_malloc_pages’?
  160 |         .page = snd_pcm_lib_get_vmalloc_page,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 snd_pcm_lib_malloc_pages
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-6.14.0-36-generic/scripts/Makefile.build:207: driver/headset.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.14.0-36-generic/Makefile:1997: .] Error 2
make[1]: *** [/usr/src/linux-headers-6.14.0-36-generic/Makefile:251: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/xone/unknown/build'
make: *** [Makefile:251: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.14.0-36-generic'
```

i saw the dependencies list above

<img width="416" height="283" alt="Image" src="https://github.com/user-attachments/assets/aa6f2059-0261-49ed-b333-deb806b274e9" />

also. Just confirm that the usb is being recognized

```
tntramp@tntramp-MS-7C91:/home/code/xone$ sudo dmesg
[13341.660343] usb 3-3: USB disconnect, device number 6
[13350.045437] usb 3-3: new high-speed USB device number 7 using xhci_hcd
[13350.171674] usb 3-3: New USB device found, idVendor=045e, idProduct=02fe, bcdDevice= 1.00
[13350.171679] usb 3-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[13350.171682] usb 3-3: Product: XBOX ACC
[13350.171684] usb 3-3: Manufacturer: Microsoft Inc.
[13350.171686] usb 3-3: SerialNumber: 402592
[13350.295741] usb 3-3: reset high-speed USB device number 7 using xhci_hcd
[13350.431551] mt76x2u 3-3:1.0: ASIC revision: 76320044
[13350.504820] mt76x2u 3-3:1.0: ROM patch build: 20141115060606a
[13350.674415] workqueue: hub_event hogged CPU for >10000us 4 times, consider switching to WQ_UNBOUND
[13350.684944] mt76x2u 3-3:1.0: Firmware Version: 0.0.00
[13350.684948] mt76x2u 3-3:1.0: Build: 1
[13350.684950] mt76x2u 3-3:1.0: Build Time: 201507311614____
[13351.071754] mt76x2u 3-3:1.0: error: MCU resp evt:9 seq:1-0
[13351.071793] mt76x2u 3-3:1.0: error: MCU resp evt:9 seq:1-0
[13351.071833] mt76x2u 3-3:1.0: error: MCU resp evt:9 seq:1-0
[13351.608742] ieee80211 phy4: Selected rate control algorithm 'minstrel_ht'
[13351.620667] mt76x2u 3-3:1.0 wlx6c5d3a17d7f1: renamed from wlan0
[13353.244227] usb 3-3: USB disconnect, device number 7
[13363.365673] mt76x2u 3-3:1.0: MAC RX failed to stop
[13363.866464] usb 3-3: new high-speed USB device number 8 using xhci_hcd
[13363.992682] usb 3-3: New USB device found, idVendor=045e, idProduct=02fe, bcdDevice= 1.00
[13363.992686] usb 3-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[13363.992689] usb 3-3: Product: XBOX ACC
[13363.992692] usb 3-3: Manufacturer: Microsoft Inc.
[13363.992694] usb 3-3: SerialNumber: 402592
[13364.116604] usb 3-3: reset high-speed USB device number 8 using xhci_hcd
[13364.252559] mt76x2u 3-3:1.0: ASIC revision: 76320044
[13364.325817] mt76x2u 3-3:1.0: ROM patch build: 20141115060606a
[13364.488457] workqueue: hub_event hogged CPU for >10000us 5 times, consider switching to WQ_UNBOUND
[13364.498948] mt76x2u 3-3:1.0: Firmware Version: 0.0.00
[13364.498952] mt76x2u 3-3:1.0: Build: 1
[13364.498954] mt76x2u 3-3:1.0: Build Time: 201507311614____
[13364.887262] mt76x2u 3-3:1.0: error: MCU resp evt:9 seq:1-0
[13364.887302] mt76x2u 3-3:1.0: error: MCU resp evt:9 seq:1-0
[13364.887341] mt76x2u 3-3:1.0: error: MCU resp evt:9 seq:1-0
[13365.418753] ieee80211 phy5: Selected rate control algorithm 'minstrel_ht'
```

**Comment by TomT15** [comment]
I see i missed talking about the installed dependencies above so here they are as well

```
tntramp@tntramp-MS-7C91:/home/code/xone$ uname -r
6.14.0-36-generic
tntramp@tntramp-MS-7C91:/home/code/xone$ dpkg -l | grep dkms
ii  dkms                                          3.0.11-1ubuntu13                         all          Dynamic Kernel Module System (DKMS)
tntramp@tntramp-MS-7C91:/home/code/xone$ dpkg -l | grep curl
ii  curl                                          8.5.0-2ubuntu10.6                        amd64        command line tool for transferring data with URL syntax
ii  libcurl3t64-gnutls:amd64                      8.5.0-2ubuntu10.6                        amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libcurl4t64:amd64                             8.5.0-2ubuntu10.6                        amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
tntramp@tntramp-MS-7C91:/home/code/xone$ dpkg -l | grep cabextract
ii  cabextract                                    1.11-2                                   amd64        Microsoft Cabinet file unpacker
tntramp@tntramp-MS-7C91:/home/code/xone$ 


```

Also, note that since we are working with code and building, the directory is /home/code/xone. Nothing has been done to the directory. only git was ran from code to clone the repo

**Comment by Lawstorant** [comment]
Please post `git remote -v` from the repository folder. I'm 99% sure you downloaded the outdated one from medusalix, which would be a bit funny  since you're posting your issue in the right one :D

In amy case, if you have xone from medusalix, redownload the repository (this time, this one) amd try again

**Comment by TomT15** [comment]
hehe maybe.

i reinstalled everything.

This meant `sudo rm xone` then using git clone repo command again

Here is some more basic info and my latest attempt at making sure debug is on

```
tntramp@tntramp-MS-7C91:/home/code/xone$ uname -r
6.14.0-36-generic
```

New errors when trying to `make test` and create debug code

```
make debug &&\
	make load
make[1]: Entering directory '/home/code/xone'
make -C /lib/modules/6.14.0-36-generic/build M=$PWD clean
make[2]: Entering directory '/usr/src/linux-headers-6.14.0-36-generic'
make[3]: Entering directory '/home/code/xone'
make[3]: Leaving directory '/home/code/xone'
make[2]: Leaving directory '/usr/src/linux-headers-6.14.0-36-generic'
make -C /lib/modules/6.14.0-36-generic/build M=$PWD ccflags-y="-Og -g3 -DDEBUG"
make[2]: Entering directory '/usr/src/linux-headers-6.14.0-36-generic'
make[3]: Entering directory '/home/code/xone'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  bus/bus.o
  CC [M]  bus/protocol.o
  CC [M]  auth/auth.o
  CC [M]  auth/crypto.o
  CC [M]  driver/common.o
  CC [M]  transport/wired.o
  CC [M]  transport/dongle.o
  CC [M]  transport/mt76.o
  CC [M]  driver/gamepad.o
  CC [M]  driver/headset.o
  CC [M]  driver/chatpad.o
  CC [M]  driver/madcatz_strat.o
  CC [M]  driver/madcatz_glam.o
  CC [M]  driver/pdp_jaguar.o
  LD [M]  xone_gip_madcatz_strat.o
  LD [M]  xone_gip_madcatz_glam.o
  LD [M]  xone_gip_gamepad.o
  LD [M]  xone_gip_pdp_jaguar.o
  LD [M]  xone_wired.o
  LD [M]  xone_gip_headset.o
  LD [M]  xone_gip_chatpad.o
  LD [M]  xone_dongle.o
  LD [M]  xone_gip.o
  MODPOST Module.symvers
  CC [M]  xone_gip.mod.o
  CC [M]  .module-common.o
  CC [M]  xone_wired.mod.o
  CC [M]  xone_dongle.mod.o
  CC [M]  xone_gip_gamepad.mod.o
  CC [M]  xone_gip_headset.mod.o
  CC [M]  xone_gip_chatpad.mod.o
  CC [M]  xone_gip_madcatz_strat.mod.o
  CC [M]  xone_gip_madcatz_glam.mod.o
  CC [M]  xone_gip_pdp_jaguar.mod.o
  LD [M]  xone_gip_madcatz_strat.ko
  LD [M]  xone_gip_headset.ko
  LD [M]  xone_gip.ko
  BTF [M] xone_gip_madcatz_strat.ko
Skipping BTF generation for xone_gip_madcatz_strat.ko due to unavailability of vmlinux
  BTF [M] xone_gip_headset.ko
Skipping BTF generation for xone_gip_headset.ko due to unavailability of vmlinux
  LD [M]  xone_gip_gamepad.ko
  LD [M]  xone_gip_madcatz_glam.ko
  BTF [M] xone_gip.ko
Skipping BTF generation for xone_gip.ko due to unavailability of vmlinux
  BTF [M] xone_gip_gamepad.ko
Skipping BTF generation for xone_gip_gamepad.ko due to unavailability of vmlinux
  BTF [M] xone_gip_madcatz_glam.ko
Skipping BTF generation for xone_gip_madcatz_glam.ko due to unavailability of vmlinux
  LD [M]  xone_wired.ko
  LD [M]  xone_gip_pdp_jaguar.ko
  BTF [M] xone_wired.ko
Skipping BTF generation for xone_wired.ko due to unavailability of vmlinux
  BTF [M] xone_gip_pdp_jaguar.ko
Skipping BTF generation for xone_gip_pdp_jaguar.ko due to unavailability of vmlinux
  LD [M]  xone_dongle.ko
  LD [M]  xone_gip_chatpad.ko
  BTF [M] xone_gip_chatpad.ko
Skipping BTF generation for xone_gip_chatpad.ko due to unavailability of vmlinux
  BTF [M] xone_dongle.ko
Skipping BTF generation for xone_dongle.ko due to unavailability of vmlinux
make[3]: Leaving directory '/home/code/xone'
make[2]: Leaving directory '/usr/src/linux-headers-6.14.0-36-generic'
make[1]: Leaving directory '/home/code/xone'
make[1]: Entering directory '/home/code/xone'
./modules_load.sh unload
./modules_load.sh
Loading xone_gip.ko
insmod: ERROR: could not insert module xone_gip.ko: Key was rejected by service
Loading xone_wired.ko
insmod: ERROR: could not insert module xone_wired.ko: Key was rejected by service
Loading xone_dongle.ko
insmod: ERROR: could not insert module xone_dongle.ko: Key was rejected by service
Loading xone_gip_gamepad.ko
insmod: ERROR: could not insert module xone_gip_gamepad.ko: Key was rejected by service
Loading xone_gip_headset.ko
insmod: ERROR: could not insert module xone_gip_headset.ko: Key was rejected by service
Loading xone_gip_chatpad.ko
insmod: ERROR: could not insert module xone_gip_chatpad.ko: Key was rejected by service
Loading xone_gip_madcatz_strat.ko
insmod: ERROR: could not insert module xone_gip_madcatz_strat.ko: Key was rejected by service
Loading xone_gip_madcatz_glam.ko
insmod: ERROR: could not insert module xone_gip_madcatz_glam.ko: Key was rejected by service
Loading xone_gip_pdp_jaguar.ko
insmod: ERROR: could not insert module xone_gip_pdp_jaguar.ko: Key was rejected by service
make[1]: *** [Makefile:18: load] Error 1
make[1]: Leaving directory '/home/code/xone'
make: *** [Makefile:21: test] Error 2
```

**Comment by Lawstorant** [comment]
Great, what you didn't do is provide me the `git remote -v`. I presume you re-pulled the right repo.

I'm not familiar with CosmicOS but it seems like it's based on ubuntu right? So this isn't an issue with xone anymore. You should google `Key was rejected by service`

Do you use Secure Boot? If so, `https://github.com/dkms-project/dkms#secure-boot` as linked in Readme

**Comment by TomT15** [comment]
tntramp@tntramp-MS-7C91:/home/code/xone$ git remote -v
origin	https://github.com/dlundqvist/xone (fetch)
origin	https://github.com/dlundqvist/xone (push)

**Comment by Lawstorant** [comment]
Again, do you have secure boot enabled on your PC? If yes, testing won't work so just install xone normally and set up secure boot like in the guide I linked previously.

**Comment by TomT15** [comment]
Oh you added a question about secure boot post comment. I'm sure it's on now. Post install I probably turned it on. Thanks for sending over the link on the secure boot stuff. I'll take a look at this tonight
