### PR TITLE
Support 5.13 and 5.15

### PR DESCRIPTION
**Pull request by SavageCore**
The following error was found by @Levistras

```
(deck@steamdeck xone-v0.3-19-gcc63d27)$ sudo ./install.sh
Driver is already installed!
Installing xone unknown...
Sign command: /usr/lib/modules/5.13.0-valve37-1-neptune/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Creating symlink /var/lib/dkms/xone/unknown/source -> /usr/src/xone-unknown

Building module:
Cleaning build area...
make -j8 KERNELRELEASE=5.13.0-valve37-1-neptune -C /usr/lib/modules/5.13.0-valve37-1-neptune/build M=/var/lib/dkms/xone/unknown/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.13.0-valve37-1-neptune (x86_64)
Consult /var/lib/dkms/xone/unknown/build/make.log for more information.
DKMS make.log for xone-unknown for kernel 5.13.0-valve37-1-neptune (x86_64)
Thu Nov  2 11:06:08 PM EDT 2023
make: Entering directory '/usr/lib/modules/5.13.0-valve37-1-neptune/build'
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/wired.o
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/dongle.o
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/mt76.o
  CC [M]  /var/lib/dkms/xone/unknown/build/bus/bus.o
  CC [M]  /var/lib/dkms/xone/unknown/build/bus/protocol.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/common.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/gamepad.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/headset.o
/var/lib/dkms/xone/unknown/build/bus/bus.c:167:19: error: initialization of ‘int (*)(struct device *)’ from incompatible pointer type ‘void (*)(struct device *)’ [-Werror=incompatible-pointer-types]
  167 |         .remove = gip_bus_remove_compat,
      |                   ^~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/xone/unknown/build/bus/bus.c:167:19: note: (near initialization for ‘gip_bus_type.remove’)
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:272: /var/lib/dkms/xone/unknown/build/bus/bus.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1847: /var/lib/dkms/xone/unknown/build] Error 2
make: Leaving directory '/usr/lib/modules/5.13.0-valve37-1-neptune/build'
```

This happens on SteamOS 3.4 (Stable) but not for me on 3.5 (Preview)

Reverting 603688daafe2bff5eb8ca0645964d0f53afbe3ce and 3d34e57e3f47539a7672af00bcd070c4f94c6bd6 allows us both to compile again.

### CODE REVIEW

**Comment by SavageCore** [comment]
I've just seen #4. Maybe we need a compat function for 5.13 and 5.15 separately?

**Comment by SavageCore** [comment]
Not at all familiar with C, I've submitted the code as far as I got but being on 5.13 doesn't like the 5.15 compat function being defined

```
(deck@steamdeck xone)$ sudo ./install.sh
[sudo] password for deck:
Driver is already installed!
Installing xone v0.3-19-gcc63d27...
Sign command: /usr/lib/modules/5.13.0-valve37-1-neptune/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j8 KERNELRELEASE=5.13.0-valve37-1-neptune -C /usr/lib/modules/5.13.0-valve37-1-neptune/build M=/var/lib/dkms/xone/v0.3-19-gcc63d27/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.13.0-valve37-1-neptune (x86_64)
Consult /var/lib/dkms/xone/v0.3-19-gcc63d27/build/make.log for more information.
DKMS make.log for xone-v0.3-19-gcc63d27 for kernel 5.13.0-valve37-1-neptune (x86_64)
Fri Nov  3 02:02:31 AM EDT 2023
make: Entering directory '/usr/lib/modules/5.13.0-valve37-1-neptune/build'
  CC [M]  /var/lib/dkms/xone/v0.3-19-gcc63d27/build/transport/wired.o
  CC [M]  /var/lib/dkms/xone/v0.3-19-gcc63d27/build/transport/dongle.o
  CC [M]  /var/lib/dkms/xone/v0.3-19-gcc63d27/build/transport/mt76.o
  CC [M]  /var/lib/dkms/xone/v0.3-19-gcc63d27/build/bus/bus.o
  CC [M]  /var/lib/dkms/xone/v0.3-19-gcc63d27/build/bus/protocol.o
  CC [M]  /var/lib/dkms/xone/v0.3-19-gcc63d27/build/driver/common.o
  CC [M]  /var/lib/dkms/xone/v0.3-19-gcc63d27/build/driver/gamepad.o
  CC [M]  /var/lib/dkms/xone/v0.3-19-gcc63d27/build/driver/headset.o
/var/lib/dkms/xone/v0.3-19-gcc63d27/build/bus/bus.c:178:15: error: initialization of ‘int (*)(struct device *)’ from incompatible pointer type ‘void (*)(struct device *)’ [-Werror=incompatible-pointer-types]
  178 |     .remove = gip_bus_remove_compat_15,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/xone/v0.3-19-gcc63d27/build/bus/bus.c:178:15: note: (near initialization for ‘gip_bus_type.remove’)
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:272: /var/lib/dkms/xone/v0.3-19-gcc63d27/build/bus/bus.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1847: /var/lib/dkms/xone/v0.3-19-gcc63d27/build] Error 2
make: Leaving directory '/usr/lib/modules/5.13.0-valve37-1-neptune/build'
```

**Comment by dlundqvist** [comment]
Please squash all of them so there is one commit just adding separate code for 5.13 and below.

**Comment by SavageCore** [comment]
Squashed

**Comment by SavageCore** [comment]
Had the check for 1.13 or lower incorrect. Works great on 1.13 (SteamOS 3.4 Stable). 

1.15 needs testing. @pallaswept, would you mind? 

Cheers all

**Comment by pallaswept** [comment]
I'll try it out now....

**Comment by pallaswept** [comment]
Builds OK on kernel 
Linux version: 5.14.21-150500.53-default #1 SMP PREEMPT_DYNAMIC Wed May 10 07:56:26 UTC 2023 (b630043) 
and 
Linux version: 6.5.9-1-default #1 SMP PREEMPT_DYNAMIC Wed Oct 25 10:31:37 UTC 2023 (29edc7c)

File: bus/bus.c [hunk 1]
```diff
@@ -152,8 +152,15 @@ static void gip_bus_remove(struct device *dev)
 		drv->remove(client);
 }
 
-#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0)
-static void gip_bus_remove_compat(struct device *dev)
+#if LINUX_VERSION_CODE <= KERNEL_VERSION(5, 13, 0)
+static int gip_bus_remove_compat_13(struct device *dev)
```
Comment (dlundqvist) [inline bus/bus.c:156]: There's only gonna be one of these callbacks, so no need to suffix with version. Name them the same is fine.

File: bus/bus.c [hunk 2]
```diff
@@ -163,8 +170,10 @@ static struct bus_type gip_bus_type = {
 	.name = "xone-gip",
 	.match = gip_bus_match,
 	.probe = gip_bus_probe,
-#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0)
```
Comment (dlundqvist) [inline bus/bus.c:166]: With the above change only check for kernel below 5.15.0 is needed, just as it already is.

**Review by dlundqvist — CHANGES_REQUESTED** [review]

File: bus/bus.c (hunk 2 above)
Comment (SavageCore) [reply bus/bus.c:166]: I see what you mean, that's nice and clean! Will force push in a moment.

**Comment by dlundqvist** [comment]
Thanks for the fix. Sorry for the delay.

**Comment by pallaswept** [comment]
> Sorry for the delay.

Not at all mate, thanks for maintaining this for us :) It's packaged up nicely for openSUSE with both kernel versions now. How's things on the SteamOS front, @SavageCore ?
