### ISSUE TITLE
xpad-noone doesn't build on newer kernels

### ISSUE THREAD

**Issue by k8ieone** [dlundqvist/xone#174]
Not exactly an xone issue, more to do with xpad-noone.

```
==> dkms install --no-depmod xpad-noone-git/r8.6970c40 -k 6.12.74-1-lts
==> dkms install --no-depmod xpad-noone-git/r8.6970c40 -k 6.18.9-zen1-2-zen

Error! Bad return status for module build on kernel: 6.18.9-zen1-2-zen (x86_64)
Consult /var/lib/dkms/xpad-noone-git/r8.6970c40/build/make.log for more information.
==> WARNING: `dkms install --no-depmod xpad-noone-git/r8.6970c40 -k 6.18.9-zen1-2-zen' exited 10
```

The build log contains

```
DKMS (dkms-3.3.0) make.log for xpad-noone-git/r8.6970c40 for kernel 6.18.9-zen1-2-zen (x86_64)
Fri Feb 20 01:52:00 PM CET 2026

Building module(s)
# command: make -j12 KERNELRELEASE=6.18.9-zen1-2-zen -C /usr/lib/modules/6.18.9-zen1-2-zen/build M=/var/lib/dkms/xpad-noone-git/r8.6970c40/build
make: Entering directory '/usr/lib/modules/6.18.9-zen1-2-zen/build'
make[1]: Entering directory '/var/lib/dkms/xpad-noone-git/r8.6970c40/build'
  CC [M]  xpad.o
xpad.c: In function ‘xpad_led_probe’:
xpad.c:1144:24: error: implicit declaration of function ‘ida_simple_get’ [-Wimplicit-function-declaration]
 1144 |         xpad->pad_nr = ida_simple_get(&xpad_pad_seq, 0, 0, GFP_KERNEL);
      |                        ^~~~~~~~~~~~~~
xpad.c:1167:9: error: implicit declaration of function ‘ida_simple_remove’ [-Wimplicit-function-declaration]
 1167 |         ida_simple_remove(&xpad_pad_seq, xpad->pad_nr);
      |         ^~~~~~~~~~~~~~~~~
make[3]: *** [/usr/lib/modules/6.18.9-zen1-2-zen/build/scripts/Makefile.build:287: xpad.o] Error 1
make[2]: *** [/usr/lib/modules/6.18.9-zen1-2-zen/build/Makefile:2009: .] Error 2
make[1]: *** [/usr/lib/modules/6.18.9-zen1-2-zen/build/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/xpad-noone-git/r8.6970c40/build'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/6.18.9-zen1-2-zen/build'

# exit code: 2
# elapsed time: 00:00:02
```

**Comment by Lawstorant** [comment]
https://github.com/forkymcforkface/xpad-noone

**Comment by k8ieone** [comment]
Yes, that's the xpad-noone I'm using. More specifically this AUR package: https://aur.archlinux.org/packages/xpad-noone-git

It uses the forkymcforkface repo.

**Comment by Lawstorant** [comment]
Yes, so create the issue there

**Comment by k8ieone** [comment]
I would except the issues are disabled there 😅

Sorry, but this seemed like the closest place to report an issue like this. I would at least ping @forkymcforkface but GitHub doesn't seem to allow that unless the person already participates in the repo.

**Comment by k8ieone** [comment]
Ah, nevermind, the ping worked! Terrible UX... 😔

**Comment by k8ieone** [comment]
This turned out to be an issue on my end, sorry about the false alarm 😓
