### ISSUE TITLE
bug: fails to build on 7.0.0 kernel

### ISSUE THREAD

**Issue by abraemer** [dlundqvist/xone#211]
```
$ cat /var/lib/dkms/xone/0.4.5/build/make.log
DKMS make.log for xone-0.4.5 for kernel 7.0.0-28-generic (x86_64)
Sun 19 Jul 08:56:43 CEST 2026
make: Entering directory '/usr/src/linux-headers-7.0.0-28-generic'
make[1]: Entering directory '/var/lib/dkms/xone/0.4.5/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0
warning: pahole version differs from the one used to build the kernel
  The kernel was built with: 125
  You are using:             0
  CC [M]  bus/bus.o
  CC [M]  bus/protocol.o
  CC [M]  auth/auth.o
  CC [M]  auth/crypto.o
  CC [M]  driver/common.o
  CC [M]  transport/wired.o
  CC [M]  transport/dongle.o
  CC [M]  transport/mt76.o
  CC [M]  driver/gamepad.o
  CC [M]  driver/headset.o
  CC [M]  driver/chatpad.o
  CC [M]  driver/madcatz_strat.o
bus/bus.c: In function ‘gip_create_adapter’:
bus/bus.c:150:20: error: implicit declaration of function ‘ida_simple_get’ [-Werror=implicit-function-declaration]
  150 |         adap->id = ida_simple_get(&gip_adapter_ida, 0, 0, GFP_KERNEL);
      |                    ^~~~~~~~~~~~~~
bus/bus.c:181:9: error: implicit declaration of function ‘ida_simple_remove’ [-Werror=implicit-function-declaration]
  181 |         ida_simple_remove(&gip_adapter_ida, adap->id);
      |         ^~~~~~~~~~~~~~~~~
  CC [M]  driver/madcatz_glam.o
  CC [M]  driver/pdp_jaguar.o
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-7.0.0-28-generic/scripts/Makefile.build:289: bus/bus.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/src/linux-headers-7.0.0-28-generic/Makefile:2115: .] Error 2
make[1]: *** [/usr/src/linux-headers-7.0.0-28-generic/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/xone/0.4.5/build'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-7.0.0-28-generic'
```
Per Claude the `ida_simple_get` and `ida_simple_remove` API was removed.

Note that this leads to kernel panics when Ubuntu tries to update the kernel because the initrd doesn't get created and the symlink to the current version points to nothing.

**Comment by abraemer** [comment]
Nvm, it is fixed here already. My version was just outdated. Sorry for the noise.
